### ISSUE TITLE
feat: 챗봇

### ISSUE THREAD

**Issue by yongaricode** [TEAM-ZIP/Frontend#4]
## 🛠️ Description for development features
챗봇

## 📝 Todo-lists
- [x] 챗봇 UI
- [x] 사용자 메세지 화면에 렌더링
- [ ] 응답 메세지 화면에 띄우기
- [ ] Open AI 응답을 위해 백엔드 코드와 연결
